silent unused variable warning
such as:
> error: variable 'sleep_cnt' set but not used [-Werror,-Wunused-but-set-variable]

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>