test: Fix compilation error for ServiceType_T
While compiling with clang, the following errors are emitted:

 CC       test-main.o
main.c:3843:27: error: implicit conversion from enumeration
type 'enum QzDirection_E' to different enumeration type 'ServiceType_T'
[-Werror,-Wenum-conversion]
                service = QZ_DIR_COMPRESS;
                        ~ ^~~~~~~~~~~~~~~
main.c:3845:27: error: implicit conversion from enumeration type
'enum QzDirection_E' to different enumeration type 'ServiceType_T'
[-Werror,-Wenum-conversion]
                service = QZ_DIR_DECOMPRESS;
                        ~ ^~~~~~~~~~~~~~~~~
main.c:3847:27: error: implicit conversion from enumeration type
'enum QzDirection_E' to different enumeration type 'ServiceType_T'
[-Werror,-Wenum-conversion]
                service = QZ_DIR_BOTH;
                        ~ ^~~~~~~~~~~

Since ServiceType_T enum defines the constants COMP, DECOMP and
BOTH, use these definitions instead.

Change-Id: I476480da295f04eeb1a49f1b4bac5a3000096958
Signed-off-by: Patrik Flykt <patrik.flykt@intel.com>
Signed-off-by: Chengfei Zhu <chengfei.zhu@intel.com>