Remove unused variable.
This fixes compilation errors such as this:

Making all in utils
make[1]: Entering directory '/data1/home/ipuustin/.cache/bazel/_bazel_ipuustin/dcbd858b6cccc7f6a21c2f4a004129a4/sandbox/linux-sandbox/878/execroot/envoy/bazel-out/k8-fastbuild/bin/external/envoy/bazel/foreign_cc/qatzip.build_tmpdir/utils'
  CC       qzip-qzip_7z.o
qzip_7z.c:2828:9: error: variable 'total_files' set but not used [-Werror,-Wunused-but-set-variable]
    int total_files = 0;
        ^
1 error generated.
make[1]: *** [Makefile:498: qzip-qzip_7z.o] Error 1

Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>