QATAPP-26588: Remove unused variable.
This fixes compilation errors such as this:

qzip_7z.c:2828:9: error: variable 'total_files' set but not used [-Werror,-Wunused-but-set-variable]
    int total_files = 0;

Change-Id: Iedcf15c13748ade0c676e499c00811fe4bf971ff
Signed-off-by: Ismo Puustinen <ismo.puustinen@intel.com>
Signed-off-by: Chengfei Zhu <chengfei.zhu@intel.com>