QATAPP-27086: Fixed compile error for GCC-4.8.5
When using GCC-4.8.5 to compile qatzip.c, it will report compile
error "qatzip.c:1063:5: error: missing braces around initializer
[-Werror=missing-braces] QzSessionParamsDeflate_T temp = {0};
qatzip.c:1063:5: error: (near initialization for'temp.common_params')
[-Werror=missing-braces]".

Change-Id: I7891bc4c7b9fd9e52b210e867a3a6e43460f047e
Signed-off-by: Chengfei Zhu <chengfei.zhu@intel.com>